language: node_js
node_js:
- '6'
before_deploy:
- echo 'before-deploy:'
- npm run build
- echo src
- ls -lR src
- echo dist
- ls -lR dist
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: TxtGxT+Ihvne2MTrGHqVtSEgCDHZQRNyGYOxu6HqSLJn+OJVTiFrSb5teoXLRqRmFs7YlaYWpuiUSEd+I3c2x23kR4TuQNR8V5ur64LjBUAC2t3HKvHXAxuYJom9zOA6x6db2s3pPbM/t2geRwWf0xF3GZV82Ll4QsvxUYU/Eccb1Cl4ZKJGcdT0hdZt7jM2E0I4QxsnJlsf31TnDEe+9fXl2r0xZTM/jrC3uGMCxVWPvIuCKoDBe0vVyOyPwI1769ds92pxUrEMRlUrkzxMvtk83zmjB6Mkp2V0YZyaZwfgH7QGJ+GS6TN55pbdCl6cCHzr0gq3ZYiQTEveIuh7MFIcI3kqvNt0dQnpM+puQEWSb14yJlIskjt+mLIw08YlI+6fpslPSA4Lt5hHgnckj+jghkypZOG1FTdEna66v42Y9644zwsPzd3NURTbuf5U2Bib727eQSBAfQ4UMpdVJeZpDgZe7YhNchZPd6pSQhoUYgQW1Yz6FKmj+u7yRVBkBggo4NlF1xZlN0dahd0B8srIuzQaWDVHDP993gponZlmEaKiK0hyRgtuVlLGkVyK+TXoqvbV857olmjTQMCe9jWWA3HZ8ZxunsyATPNRSQ5uArOpVLGfK8mcS6U9dJCsvBNTS9qV2rL10Xz8M0cKCYE6vUAcXfp1ZPizKl6krhc=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
