language: node_js
node_js:
- lts/*
before_deploy:
- echo 'before-deploy:'
- npm run build
- echo src
- ls -lR src
- echo dist
- ls -lR dist
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: aemyzYsL3xBeDUVC4d7QQsc9BTLBE6Gsyl9bvwt1r22e8up5XfZz0BHesNnRsTfN7djGXioISDGNSgSVEuO3LX+8EReJnIlfz18KVbr6trxtkJ32Ya1Nk3fangs/gRYyTKA+P0J/OBfXU22b9MFLbVmrXpvlzL/O2oMbrvadHlXvWa7Svzhjdi0NWVvnUtZiiQEP23d0ZVdReAqKgDI3HZpHcNjWHLEsmUUoPJ8QiTHcwADEVmZPRdr8imhHxnCRFYyLRffaD5k3RI2uo6F/2eQGBJ9xcFmTod4l0OC/rgqv8MHgflCK7I0vxsZivLK4NHwn1isufLa0rh1BZaoavWpdQzKhLy9RjGwXftFyKKM5sqYfKZOsa1KBN/iQofJhlfPH3ZuvwTdgcSPmtBh2M45ilWaQGai2iOAAsIP5Hj9+b5o/S7pi5lHV5DSPhaB1MDpo+gJm2TAJAHX7aPVIeF2J87rR7dWmPn+Uj4OhFlqBd3yFhOlfil+Mi/LLD3zQhT1f7CeI3xt3deS8pmTa8tMkW0oz1GNWetMW19ZSJx30DhMnaqveaOK6XgVeTCB8OHAPA/pFbA4E+lscGK3/8XQEe4r/NUyrMd+JRCsrxh3l5Vpue2p8x3PdybvKtESVECbaW+ouFDow8zzTYlcoWSopEINTLoZODfDl+UpCxWs=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
