language: node_js
node_js:
- lts/*
before_deploy:
- echo 'before-deploy:'
- npm run build
- echo src
- ls -lR src
- echo dist
- ls -lR dist
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: lp4flLvFbFdqYOt2gKqhTEY+WmEeC0JiP/mEylsTcWWA9YzyKsFLvSodkDn4dXY6ctA5z3NrehOAaRmJeFgoPojseDWNqB4A/LXNkBeNqvMqS79UFD+CouBJ0EbfdQH6BWqkE91GJO1okEi+E9xc/2cNuUPEyhmhQ3lAsjQPx7exq8HmdbkyXFsDK+6mPV3hojqbB9avZH5paykovbUA8OdapgAxQ6OXbI2+LMrRfx9eixiOpqJFzInP5Cjb8Iq5HKHHMkxBLPHuUA7PxZkKUETTmlFdTUx4TXT1z9kl4getKBxWxopvOvuX3eFICKsm71PXCGzWDBdjE/WSWzQtSN7P8vkuQDS5llqT6sPrv1Q9T2hPOJZk8ry4Q7Jq7YF2h5kv4WCvW+PnKPbFcr7bSIvYcdDB5APdLE6rTvs+bwf1a1+HIouv39BL7b02tL/czuh0QvpeuSlUz8oRlaCnRSZZ8cvJSJuPPz5VPLnozQeDxASCu98kjT+J7fk8Cc95aetZAuK2qS/zQixGtQIIkL/ZIB2Qj8u8LadU9HyTkMkptLBtXQgz2EtCinJvXDVWo+X09QUicCzPKnK0vEf/ImA2qOf1jUPvO88KSAaTIcgvqJtNgi+RrzDvTgCnYmsum7D38xnukRWI2mg4NLlqFtWYGr9e9adgFBLJNxBttS8=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
