packageExtensions:
  xo@0.49.0:
    dependencies:
      webpack: 5.73.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

nodeLinker: node-modules
